name: build-and-test
run-name: Build and test ${{ github.ref_type }} ${{ github.ref_name }}
on: push
jobs:
  cmake:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: sudo apt-get install -y git cmake ninja-build
      - name: info
        run: |
          git version
          cmake --version
          ninja --version
      - uses: actions/checkout@v4
      - name: build-and-test
        run: |
          cp "./CMakeUserPresets.template.json" "./CMakeUserPresets.json"
          cmake --workflow --preset user-test
