on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "lepus2589/LoadStaticSharedTargets"
          # source_branch: "refs/remotes/source/*:refs/tags/*"
          destination_repo: "${{ secrets.MIRROR_DESTINATION_REPO_URL }}"
          # destination_branch: "refs/heads/*:refs/tags/*"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
